feat: import auto complete
appworks-lab/pack pull request #905
Opened 2021-07-15 06:36 UTC by GiveMe-A-Name

import auto complete

2021-07-19 02:28 UTC, luhc228 commented
看一下冲突

2021-07-19 02:34 UTC, luhc228 commented on extensions/material-helper/src/importAutoComplete/getAlreadyImportSet.ts
> +    // ignore
把 error 也打印出来吧。

2021-07-19 02:34 UTC, luhc228 commented on extensions/material-helper/src/importAutoComplete/getCompletionItemsFromFilename/getItemsFromStoreFile.ts
> +    // ignore
把错误也打印出来？

2021-07-19 03:37 UTC, fyangstudio requested changes
逻辑建议上分成
getStoreItems (store model)
getFrameworkItems (rax、ice)
getComponentItems 
getStyleItems (补充：发现用户在编辑 jsx 文件时同时没引 stlye 文件时触发 )
getFileItems (现 file 部分)

同时 最好写点注释，补充一些注释上的示例  可以让代码有更好的可读性

2021-07-19 03:37 UTC, fyangstudio commented on extensions/material-helper/src/importAutoComplete/getCompletionItemsFromDirectory/getItemsFromFile/index.ts
> +export default (
建议写些注释，列举一些例子。

2021-07-19 03:37 UTC, fyangstudio commented on extensions/material-helper/src/importAutoComplete/getCompletionItemsFromDirectory/getItemsFromFolder/getItemsFromComponentsFolder.ts
> +    alreadyImportSet.has('react')
或者还有 rax?

2021-07-19 03:37 UTC, fyangstudio commented on extensions/material-helper/src/importAutoComplete/getFilenameWithoutExtname.ts
> +  if (['.js', '.ts', '.jsx', '.tsx'].includes(path.extname(fileName))) {
还有 style 文件。  css scss .

2021-07-19 08:41 UTC, GiveMe-A-Name commented on extensions/material-helper/src/importAutoComplete/getCompletionItemsFromDirectory/getItemsFromFolder/getItemsFromComponentsFolder.ts
> +    alreadyImportSet.has('react')
done

2021-07-19 08:45 UTC, GiveMe-A-Name commented on extensions/material-helper/src/importAutoComplete/getFilenameWithoutExtname.ts
> +  if (['.js', '.ts', '.jsx', '.tsx'].includes(path.extname(fileName))) {
```js
import xxx from './utils' // utils.ts
import styles from './index.module.scss'
```
考虑到在实际项目中，`'.js'`, `'.ts'`, `'.jsx'`, `'.tsx'`扩展名可以省略，对于开发者有更好的体验，所以对js相关扩展名做了特别处理，其他文件不做处理。

2021-07-19 08:49 UTC, GiveMe-A-Name commented on extensions/material-helper/src/importAutoComplete/getAlreadyImportSet.ts
> +    // ignore
done

2021-07-19 08:49 UTC, GiveMe-A-Name commented on extensions/material-helper/src/importAutoComplete/getCompletionItemsFromDirectory/getItemsFromFile/index.ts
> +export default (
done

2021-07-21 02:31 UTC, fyangstudio approved these changes

2021-07-21 02:31 UTC, merged